/** 集中错误码：service 抛出、api 二次包装、页面 toast 展示均引用此处 */
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DMX_ADDRESS_CONFLICT: "DMX_ADDRESS_CONFLICT",
  DMX_ADDRESS_OUT_OF_RANGE: "DMX_ADDRESS_OUT_OF_RANGE",
  FIXTURE_CODE_DUPLICATED: "FIXTURE_CODE_DUPLICATED",
  CUE_NOT_FOUND: "CUE_NOT_FOUND",
  FIXTURE_NOT_FOUND: "FIXTURE_NOT_FOUND",
  TIMELINE_OVERLAP: "TIMELINE_OVERLAP",
  TRACK_LOCKED: "TRACK_LOCKED",
  TRACK_NOT_FOUND: "TRACK_NOT_FOUND",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED",
  IMPORT_INVALID: "IMPORT_INVALID"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
