export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DMX_ADDRESS_OVERLAP: "DMX_ADDRESS_OVERLAP",
  DMX_ADDRESS_OUT_OF_RANGE: "DMX_ADDRESS_OUT_OF_RANGE",
  TRACK_OVERLAP: "TRACK_OVERLAP",
  TRACK_LAYER_LOCKED: "TRACK_LAYER_LOCKED",
  CUE_NOT_FOUND: "CUE_NOT_FOUND",
  FIXTURE_NOT_FOUND: "FIXTURE_NOT_FOUND",
  STORAGE_UNAVAILABLE: "STORAGE_UNAVAILABLE",
  IMPORT_PAYLOAD_INVALID: "IMPORT_PAYLOAD_INVALID"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
